owner: HackTJ
repo: status

sites:
  - name: HackTJ
    url: https://hacktj.org
    icon: https://hacktj.org/favicon.png
  - name: HackTJ 11.0
    url: https://hacktj.org/2024
  - name: HackTJ 10.0
    url: https://hacktj.org/2023
  - name: HackTJ 9.0
    url: https://hacktj.org/2022
  - name: HackTJ 8.0
    url: https://hacktj.org/2021
    icon: https://hacktj.org/2021/favicon.ico
  - name: HackTJ 7.5
    url: https://hacktj.org/2020v2
    icon: https://hacktj.org/2020v2/favicon.ico
  - name: HackTJ 7.0
    url: https://hacktj.org/2020
    icon: https://hacktj.org/2020/favicon.ico
  - name: HackTJ 6.0
    url: https://hacktj.org/2019
    icon: https://hacktj.org/2019/img/logo2.png
  - name: HackTJ 5.0
    url: https://hacktj.org/2018
    icon: https://hacktj.org/2018/img/favicon.png
  - name: HackTJ 4.0
    url: https://hacktj.org/2017
    icon: https://hacktj.org/2017/img/favicon.png
  - name: HackTJ 3.0
    url: https://hacktj.org/2016
    icon: https://hacktj.org/2016/img/favicon.png
  - name: HackTJ 2.0
    url: https://hacktj.org/2015
    icon: https://hacktj.org/2015/img/favicon.png

status-website:
  cname: status.hacktj.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/HackTJ/status/master/logo.svg
  name: HackTJ Status
  introTitle: "The official HackTJ status page."
  introMessage: Real-time monitoring for HackTJ sites, powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
